
compile:
	g++ -std=c++11 float_type.cpp -o float_type -lstdc++
	g++ -std=c++11 double_type.cpp -o double_type -lstdc++
	g++ -std=c++11 long_double_type.cpp -o long_double_type -lstdc++

count_for_float:
	./float_type

count_for_double:
	./double_type

count_for_long_double:
	./long_double_type

clean:
	rm -f float_type double_type long_double_type